spring:
#  data:
#    elasticsearch:
##      repositories:
##        enabled: true
##      client:
##        reactive:
##          endpoints: 192.168.175.86:9200
#      cluster-nodes: 192.168.175.86:9200
#     # cluster-name: docker-cluster

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: druidDataSource
    url: jdbc:postgresql://192.168.175.86:5432/mrftest?currentSchema=mrf
    driver-class-name: org.postgresql.Driver
    username: sie_ems
    password: emstest
    druid:
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置多久检测一次，检测需要关闭空间连接，单位ms
      time-between-eviction-runs-millis: 60000
      # 配置一个池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      validation-query: SELECT 1 FROM DUAL
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat
      #日志用的filter:log4j
      #防御sql注入的filter:wall
      filters: stat,wall,slf4j
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #通过connectProperties属性打开mergeSql功能;慢sql记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
        #添加ip白名单
        allow: 127.0.0.1,localhost
        #黑名单，黑白名单有重复，黑优先级高
        #deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 必须启用，要不会404
        enabled: true
      web-stat-filter:
        #添加过滤规则
        url-pattern: /*
        #忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico"
        enabled: true
      async-close-connection-enable: true